name: Deploy to Render on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST https://api.render.com/deploy/srv-REPLACE_WITH_SERVICE_ID?key=${{ secrets.RENDER_API_KEY }}
